version: "3.3"

services:
  server:
    build: . 
    image: pythonserver:1.0
    ports:
      - "8000:80"
    volumes: 
      - .:/home/test
    depends_on: 
      - db
  db:
    image: postgres
    ports:
      - "6551:5432"
    environment: 
      POSTGRES_PASSWORD: password123